name: Daily GitHub Backup

on:
  schedule:
    - cron: '0 3 * * *' # Every day at 3 AM UTC (8:30 AM IST)
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get today's date
        id: get_date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Create backup zip
        run: |
          mkdir backup
          zip -r backup/website-${{ steps.get_date.outputs.date }}.zip . -x "*.git*" "node_modules/*" ".next/*"

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-backup-${{ steps.get_date.outputs.date }}
          path: backup/
          retention-days: 30
